version: '3.7'

services:
  isoskaba-back:
    build:
      context: isoskaba-back
      args:
        NODE_ENV: 'development'
    env_file:
        - .env
    command: 'npm run start:dev'
    ports:
      - 8080:8080
    volumes:
      - ./isoskaba-back:/usr/src/app
    depends_on:
      - isoskaba-db
    container_name: isoskaba-back

  isoskaba-db:
    image: postgres:9.6.3
    env_file:
      - .env-db
    volumes:
      - isoskaba-pgdata:/var/lib/postgresql/data
    container_name: isoskaba-db

volumes:
  isoskaba-pgdata:
