version: 2.1

orbs:
  node: circleci/node@3.0.0

executors:   
  build-executor:     
    working_directory: ~/app     
    machine:       
      image: ubuntu-1604:201903-01

workflows:
  heroku_deploy:
    jobs:
      - build


jobs:
  build:
    executor: build-executor
    steps:
      - checkout
      - run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
      # Bundle install dependencies
      - run: docker build -t isoskaba:latest ./isoskaba-back
      - run: docker tag isoskaba:latest registry.heroku.com/isoskaba-v3/web
      - run: docker push registry.heroku.com/isoskaba-v3/web



