version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1 # Invoke the Heroku orb

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build

jobs:
  build:
    docker:
      - image: vanhasalakuljettaja/isoskaba3.0-back
    working_directory: ~/project
    steps:
      - checkout
      # Bundle install dependencies
      - run: npm install

